# Generated by Django 4.2.4 on 2023-11-09 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_alter_accounttype_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(choices=[('SALES', 'Sales'), ('ACCOUNT', 'Accounting'), ('INVENTORY', 'Inventory'), ('ADMIN', 'Administration')], max_length=100, verbose_name='Department Name'),
        ),
    ]
