# Generated by Django 4.2.4 on 2023-11-09 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_type',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
