# Generated by Django 4.2.4 on 2023-11-15 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0009_alter_customuser_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='city',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='postal_Code',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='state',
            field=models.TextField(blank=True, null=True),
        ),
    ]
