# Generated by Django 4.2.4 on 2023-11-16 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0010_company_city_company_postal_code_company_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
