# Generated by Django 4.2.4 on 2023-11-16 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0011_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profilePic',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
