# Generated by Django 4.2.4 on 2023-11-15 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='ledger_limit',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AddField(
            model_name='ledger',
            name='ledger_limitLeft',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
