# Generated by Django 4.2.4 on 2023-11-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitOfMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(choices=[('Piece', 'Piece'), ('Liter', 'Liter'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter')], default='Piece', max_length=10)),
                ('description', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='material',
            name='unit_of_measurement',
            field=models.CharField(choices=[('Piece', 'Piece'), ('Liter', 'Liter'), ('Meter', 'Meter'), ('Centimeter', 'Centimeter')], default='Piece', max_length=10),
        ),
    ]
