# Generated by Django 4.2.4 on 2023-11-13 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commonApp', '0002_unitofmeasurement_alter_material_unit_of_measurement'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UnitOfMeasurement',
        ),
    ]
