# Generated by Django 4.2.4 on 2023-11-10 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotation',
            name='id',
        ),
        migrations.AlterField(
            model_name='quotation',
            name='quotation_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
