# Generated by Django 4.2.4 on 2023-11-13 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_quotation_id_alter_quotation_quotation_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('sales', 'Sales'), ('quotations', 'Quotations')], default='quotations', max_length=20)),
                ('product_name', models.CharField(max_length=255)),
                ('product_description', models.TextField()),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='bank_details',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='grand_total',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='payment_due_date',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='payment_method',
        ),
        migrations.RemoveField(
            model_name='quotation',
            name='validity_accepted_by_customer',
        ),
        migrations.DeleteModel(
            name='QuotationItem',
        ),
        migrations.AddField(
            model_name='itemrow',
            name='quotation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation'),
        ),
    ]
