# Generated by Django 4.2.4 on 2023-11-14 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounting', '0001_initial'),
        ('sales', '0005_alter_itemrow_total_price_alter_itemrow_unit_price_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sale_number', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('contact_person', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('billing_address', models.TextField()),
                ('shipping_address', models.TextField(blank=True)),
                ('sale_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('tax_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('terms_and_conditions', models.TextField(blank=True)),
                ('notes_comments', models.TextField(blank=True)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sub_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('tax_total', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('final_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.ledger')),
            ],
        ),
        migrations.AddField(
            model_name='itemrow',
            name='sale',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sales'),
            preserve_default=False,
        ),
    ]
