# Generated by Django 4.2.4 on 2023-11-14 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_itemrow_sale'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrow',
            name='sale',
        ),
    ]
