# Generated by Django 4.2.4 on 2023-11-14 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0009_itemrow_sale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrow',
            name='quotation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.quotation'),
        ),
    ]
