# Generated by Django 4.2.4 on 2023-11-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0010_alter_itemrow_quotation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sales',
            old_name='expiry_date',
            new_name='delivery_date',
        ),
    ]
