# Generated by Django 4.2.4 on 2023-11-15 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0012_rename_delivery_date_sales_delivery_datesale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='advance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='trasactionDetails',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sales',
            name='trasactionType',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('neft/rtgs/upi', 'NEFT/RTGS/UPI')], max_length=20, null=True),
        ),
    ]
