# Generated by Django 4.2.4 on 2023-11-15 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0013_sales_advance_sales_trasactiondetails_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='discount',
        ),
        migrations.AlterField(
            model_name='sales',
            name='advance',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='final_amt',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='sub_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sales',
            name='tax_total',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
