# Generated by Django 4.2.4 on 2023-11-15 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0014_remove_sales_discount_alter_sales_advance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrow',
            name='entry_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('quotations', 'Quotations')], max_length=20),
        ),
    ]
